# Generated by Django 3.2.13 on 2022-08-14 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_file', models.FileField(upload_to='files')),
                ('users', models.ManyToManyField(related_name='dls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
